### ISSUE TITLE
Multiple Bags

### ISSUE THREAD

**Issue by Samaeli** [Void-Developments/void_backpacks#1]
When putting multiple bags in the config the back pack doesn't get removed when dropped

**Comment by darkets** [comment]
Fixed in commit fd13af664c5e583942ef91ed475d63a56e52c195

**Comment by Samaeli** [comment]
So now it does change the bags thank you , but upon dropping the backpack still stays on the back

**Comment by Samaeli** [comment]
https://i.imgur.com/riQIGgn.png
