### ISSUE TITLE
Upon Dropping bag it doesnt remove the component 

### ISSUE THREAD

**Issue by Samaeli** [Void-Developments/void_backpacks#2]
https://i.imgur.com/riQIGgn.png

**Comment by darkets** [comment]
I fixed this yesterday. Is your script up to date?

**Comment by Samaeli** [comment]
> I fixed this yesterday. Is your script up to date?

Yes I did fresh download

**Comment by darkets** [comment]
works as intended for me. I'm gonna need steps to reproduce this issue.

**Comment by Samaeli** [comment]
ill get a clip for you in a couple minutes or tomorrow
