### ISSUE TITLE
doesnt put on backpack

### ISSUE THREAD

**Issue by sykk** [Void-Developments/void_backpacks#3]
is this compatible with esx? i can open the bag and everything it just does not put the bag on my character

**Comment by darkets** [comment]
Does the bag not appear only when loading in the server, or always?

**Comment by sykk** [comment]
for me always. i have tried dropping and picking it back up but still will not put the backpack on character. i can open and view the backpack inventory though

**Comment by IlMicioLetale** [comment]
How to resolve? thank you
